os: linux
dist: jammy
jdk: openjdk17
language: python
python:
- '3.9'
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
jobs:
  include:
    - name: flake8
      install:
      - pip install tox
      script:
      - tox -e flake8
    - stage: deploy
      name: pypi
      if: branch ~= /\d+\.\d+\.\d+/
      install: skip
      script: skip # skip test scripts
      deploy:
        provider: pypi
        skip_cleanup: true
        user: "__token__"
        password: ${PYPI_API_TOKEN}
        on:
          tags: true
          distributions: sdist bdist_wheel
