dist: xenial
language: python
python:
- '3.6'
env:
  matrix:
  - TOX_ENV=test
  - TOX_ENV=flake8
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
install:
- pip install tox
- pip install setuptools --upgrade
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  skip_cleanup: true
  user: "__token__"
  password:
    secure: F7FzSyTUmyRmgmSHnnHrzIuVovZLplPaJwPeOtjvJ+3vYoLOd8vpbCO2+cvIfGzJAigxbc7QX3J5zSxXTioyQQ92Bb8yYkGqWD2vay64TW4waRcWHSif40b+s6/A/7cwJJru0llbPVFRXWGoBE14zzbshoD25My4pucM8JyvL4uXbXZzTKytBKSgXS7wqfdI5WivEkNvGJcuWqUoneHOvKoxjn0pbaPkFSvkRGEX6IdrloRYlBASO8juUVbeMk6a+bQTlccZ74Xbz+zfQItGO7UJTgC+pFiVbKM3VNbuU9+EktdHP/I5pRCRjICIjkWQG01jh0+WklOyfPtYZhyhRAsYzzSwMHtBaX2mwJepbiatTCwqF3PTvY6F0vQOWsVbcc9k41R+8svMgktsU4SrcybeyiQgeZk+FE4zrkysIUX0oYSBXt5ftwSBpqolhZ2ef3PepHd4y895oDwFkse/bLxYis6+UZz/LmbBUIqpzUTj/Sp9kElib/kI1QC5uEztPHfCmiNrPQjOFgnZg6Lk9IbIkYiIHrbPe3SqfgF73DxsnZsxUFZSogNAIA6qUkB5lwVz1Nt2cGZk8J7+bfvyae1y4umRrEvPBOlPPU4xqj5cyhNM7mia26+qu8RddNYvT5n4vBCcovzuRxBOeeLTY4+DreD8DairvuZlpV69DdA=
  on:
    tags: true
    distributions: sdist bdist_wheel
