os: linux
dist: jammy
language: python
python:
- '3.8'
- '3.9'
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
jobs:
  include:
    - name: test
      install:
      - pip install tox
      - pip install setuptools --upgrade
      addons:
        sonarcloud:
          organization: "ithuan"
          token: ${SONAR_TOKEN}
      script:
      - tox -e test
      - sonar-scanner
    - name: flake8
      install:
      - pip install tox
      script:
      - tox -e flake8
    - stage: deploy
      name: pypi
      install: skip
      script: skip # skip test scripts
      deploy:
        provider: pypi
        skip_cleanup: true
        user: "__token__"
        password: ${PYPI_API_TOKEN}
        on:
          tags: true
          distributions: sdist bdist_wheel
