os: linux
dist: jammy
language: python
python:
- '3.9'
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
jobs:
  include:
    - name: test
      install:
      - pip install tox
      - pip install setuptools --upgrade
      service:
      - docker
      addons:
        # For the `SONARQUBE_SCANNER_PARAMS` variable
        sonarcloud:
          token: ${SONAR_TOKEN}
      script:
      - tox -e test
      - >
        docker run --rm
          -e SONARQUBE_SCANNER_PARAMS
          -e SONAR_TOKEN="${SONAR_TOKEN}"
          -v "`pwd`:/usr/src"
          sonarsource/sonar-scanner-cli
    - name: flake8
      install:
      - pip install tox
      script:
      - tox -e flake8
    - stage: deploy
      if: branch ~= /\d+\.\d+\.\d+/
      name: pypi
      install: skip
      script: skip # skip test scripts
      deploy:
        provider: pypi
        skip_cleanup: true
        user: "__token__"
        password: ${PYPI_API_TOKEN}
        on:
          tags: true
          distributions: sdist bdist_wheel
