dist: jammy
language: python
python:
- '3.8'
- '3.9'
- '3.10'
env:
  matrix:
  - TOX_ENV=test
  - TOX_ENV=flake8
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
install:
- pip install tox
- pip install setuptools --upgrade
script:
- tox -e $TOX_ENV
jobs:
  include:
    - stage: deploy
      python: '3.10'
      install: skip
      script: skip # skip test scripts
      deploy:
        provider: pypi
        skip_cleanup: true
        user: "__token__"
        password: ${PYPI_API_TOKEN}
        on:
          tags: true
          distributions: sdist bdist_wheel
